name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000

    steps:
    - uses: actions/checkout@v2
      name: Check out code
    - name: Setup env variables
      run: cp .env.sample .env
    - uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: localhost:5000/easy-commerce-backend:latest
    - uses: addnab/docker-run-action@v3
      with:
        image: localhost:5000/easy-commerce-backend:latest
        run: python manage.py test
    # - name: Build Docker image
    #   run: docker build . --file Dockerfile --tag easy-commerce-backend:${{steps.vars.outputs.tag}}
    # - name: Run Tests
    #   run: docker exec -it web ""
